name: bf-api
channels:
  - https://conda-channel.int.geointservices.io
dependencies:
  - python=3.5.2
  - click=6.6
  - coverage=4.2
  - Flask=0.11.1
  - Flask-Cors=3.0.2
  - gunicorn=19.6.0
  - itsdangerous=0.24
  - Jinja2=2.8
  - MarkupSafe=0.23
  - psycopg2=2.6.2
  - python-dateutil=2.5.3
  - requests=2.12.1
  - requests-mock=1.1.0
  - six=1.10.0
  - SQLAlchemy=1.1.3
  - Werkzeug=0.11.11
